version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
