version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ${REPO_URI}:${IMAGE_TAG} .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - printf '{"ImageURI":"%s"}' ${REPO_URI}:${IMAGE_TAG} > imageDetail.json
      - echo "Created imageDetail.json:"
      - cat imageDetail.json
artifacts:
  files:
    - appspec.yml
    - imageDetail.json
    - scripts/**/*
